from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from ai.knowledge_engine.models import RetrievedChunk, Citation, SearchMetadata
from ai.ai_agents.models import TokenUsage, ResponseMetadata
from ai.ai_agents.intelligence_models import ComplianceIssue, ProjectHealth, ComplianceResult, QualityMetrics, Recommendation


class UploadResponse(BaseModel):
    """Response model returned after parsing and indexing an uploaded file."""

    document_id: str = Field(
        ...,
        description="The unique identifier assigned to the parsed document"
    )
    file_name: str = Field(
        ...,
        description="Name of the uploaded file"
    )
    status: str = Field(
        ...,
        description="Processing status ('indexed', 'failed', 'processing')"
    )
    message: str = Field(
        ...,
        description="Detailed description of the processing result"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extracted document metadata"
    )


class SearchResponse(BaseModel):
    """Response model containing vector similarity search results."""

    query: str = Field(
        ...,
        description="The query string executed"
    )
    results: List[RetrievedChunk] = Field(
        ...,
        description="Ranked list of matching retrieved chunks"
    )
    citations: List[Citation] = Field(
        ...,
        description="Structured citations linking chunks back to their sources"
    )
    metadata: SearchMetadata = Field(
        ...,
        description="Timing and configuration parameters used during search"
    )


class ChatResponse(BaseModel):
    """Response model containing conversational chat results."""

    query: str = Field(
        ...,
        description="The user query processed"
    )
    response: str = Field(
        ...,
        description="Text response generated by the AI Brain"
    )
    query_type: str = Field(
        ...,
        description="The semantic category classified for this query"
    )
    citations: List[Citation] = Field(
        default_factory=list,
        description="Document citations reference list backing the response context"
    )
    metadata: ResponseMetadata = Field(
        ...,
        description="Timing metrics and token usage statistics"
    )


class ComplianceResponse(BaseModel):
    """Response model containing structured specification compliance results."""

    specification_name: str = Field(
        ...,
        description="Name of the audited specification document"
    )
    compliance_score: float = Field(
        ...,
        description="Compliance ratio rating (0.0 to 1.0)"
    )
    is_compliant: bool = Field(
        ...,
        description="Whether the document is compliant based on safety thresholds"
    )
    issues_detected: List[ComplianceIssue] = Field(
        ...,
        description="List of compliance violations and missing requirements detected"
    )
    evaluated_count: int = Field(
        ...,
        description="Total requirements checked"
    )


class RecommendationResponse(BaseModel):
    """Response model containing corrective action recommendations."""

    document_id: str = Field(
        ...,
        description="The audited document ID reference"
    )
    recommendations: List[Recommendation] = Field(
        ...,
        description="List of prioritized corrective and preventative recommendations"
    )


class ReportResponse(BaseModel):
    """Response model containing structured overall project insight reports."""

    report_id: str = Field(
        ...,
        description="Unique report identifier"
    )
    project_health: ProjectHealth = Field(
        ...,
        description="Global health metrics overview"
    )
    compliance_summaries: List[ComplianceResult] = Field(
        ...,
        description="Summaries of document compliance checks"
    )
    quality_summaries: List[QualityMetrics] = Field(
        ...,
        description="Summaries of document quality validations"
    )
    recommendations: List[Recommendation] = Field(
        ...,
        description="Consolidated list of corrective recommendations"
    )
    executive_summary: str = Field(
        ...,
        description="Natural language summary text outlining key issues"
    )
    generated_at: str = Field(
        ...,
        description="Report generation ISO timestamp"
    )


class DocumentRegistryItem(BaseModel):
    """Details of a single document registered in the knowledge base."""

    document_id: str = Field(..., description="Document ID")
    file_name: str = Field(..., description="Source file name")
    status: str = Field(..., description="Document status ('registered')")
    chunk_count: int = Field(..., description="Total number of chunks indexed")
    registered_at: str = Field(..., description="Registration timestamp")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata dictionary")


class ProjectSummaryResponse(BaseModel):
    """Dashboard statistics and KB metrics."""

    document_count: int = Field(
        ...,
        description="Total number of documents registered in the system"
    )
    registered_documents: List[DocumentRegistryItem] = Field(
        ...,
        description="List of active registered document summaries"
    )
    total_chunks: int = Field(
        ...,
        description="Total chunks across all indexed documents"
    )
    health_metrics: Optional[ProjectHealth] = Field(
        default=None,
        description="Overall aggregate project health indicators"
    )


class RiskResponse(BaseModel):
    """Response model containing structured safety and schedule risks reviews."""

    document_id: str = Field(
        ...,
        description="The unique document identifier reference"
    )
    risk_level: str = Field(
        ...,
        description="Calculated risk severity category ('Critical', 'High', 'Medium', 'Low')"
    )
    risk_summary: str = Field(
        ...,
        description="Narrative summarizing identified threat indicators"
    )
    suggested_actions: List[str] = Field(
        ...,
        description="Recommended corrective action items to mitigate risks"
    )
