from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class ConversationMessage(BaseModel):
    """A single message structure in the conversation history."""

    role: str = Field(
        ...,
        description="Role of the sender ('system', 'user', 'assistant')"
    )
    content: str = Field(
        ...,
        description="Raw text content of the message"
    )
    timestamp: str = Field(
        ...,
        description="ISO 8601 timestamp of when the message was recorded"
    )


class ConversationSession(BaseModel):
    """Represents a conversation session container tracking session histories."""

    session_id: str = Field(
        ...,
        description="Unique identifier of the conversation session"
    )
    messages: List[ConversationMessage] = Field(
        default_factory=list,
        description="Chronological list of messages recorded inside the session"
    )


class AIRequest(BaseModel):
    """Incoming request parameters mapped to the AI Project Brain orchestrator."""

    query: str = Field(
        ...,
        description="The query string or question inputted by the user"
    )
    session_id: str = Field(
        ...,
        description="Target conversation session ID to recall memory"
    )
    filters: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional metadata filters to restrict search bounds in the vector store"
    )


class TokenUsage(BaseModel):
    """Token consumption metrics returned by the LLM provider."""

    prompt_tokens: int = Field(
        default=0,
        description="Tokens consumed by the prompt context"
    )
    completion_tokens: int = Field(
        default=0,
        description="Tokens generated during the LLM completion response"
    )
    total_tokens: int = Field(
        default=0,
        description="Total tokens consumed during the execution lifecycle"
    )


class ResponseMetadata(BaseModel):
    """System metrics mapping execution latencies and classification indicators."""

    query_type: str = Field(
        ...,
        description="Classified query tag (e.g. 'Compliance Query', 'Risk Query')"
    )
    latency_seconds: float = Field(
        ...,
        description="Total orchestrator execution duration in seconds"
    )
    search_latency_seconds: Optional[float] = Field(
        default=None,
        description="Retrieval search phase latency in seconds"
    )
    llm_latency_seconds: Optional[float] = Field(
        default=None,
        description="LLM network execution latency in seconds"
    )
    token_usage: Optional[TokenUsage] = Field(
        default=None,
        description="Token consumption details of the LLM execution"
    )
    model_name: str = Field(
        ...,
        description="Name of the model employed during response generation"
    )


class AIResponse(BaseModel):
    """The final structured response compiled by the AI Project Brain orchestrator."""

    query: str = Field(
        ...,
        description="Original query input"
    )
    response: str = Field(
        ...,
        description="Cleaned, structured response text generated by the AI Brain"
    )
    query_type: str = Field(
        ...,
        description="Classified category tag"
    )
    metadata: ResponseMetadata = Field(
        ...,
        description="System timing, model usage, and token consumption parameters"
    )


class LLMResponse(BaseModel):
    """Internal schema representing raw outputs generated by the LLM Client."""

    content: str = Field(
        ...,
        description="Response text generated by the model"
    )
    token_usage: TokenUsage = Field(
        ...,
        description="Calculated token usage metrics"
    )
    model_name: str = Field(
        ...,
        description="Target model identifier"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Optional provider metadata attributes returned"
    )


class PromptContext(BaseModel):
    """Unified container holding system commands and context-enriched user prompts."""

    system_prompt: str = Field(
        ...,
        description="System prompts containing instructions and strict boundaries"
    )
    user_prompt: str = Field(
        ...,
        description="User prompts mapping contextual references and conversation parameters"
    )
